name: edu_core
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  intl: ^0.18.1
  auto_size_text: ^3.0.0
  http: ^1.4.0
  pdf: ^3.10.4
  printing: ^5.12.0
  flutter_rating_bar: ^4.0.0
  file_picker: ^10.1.9
  image: ^4.0.15
  nepali_date_picker: ^6.0.2
  syncfusion_flutter_datepicker: ^20.4.49
  nepali_utils: ^3.0.8
  table_calendar: ^3.0.9
  flutter_staggered_animations: ^1.1.0
 
  shared_preferences: ^2.0.15
  
  lottie: ^2.2.0
  share_plus: ^11.0.0
  shimmer: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/school_logo.png
